import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Dark marketplace theme
        "surface-container-low": "#131313",
        "primary-container": "#98ffd9",
        "on-primary-fixed": "#004533",
        "on-error": "#490006",
        "primary-fixed-dim": "#7be2bd",
        "on-background": "#e5e5e5",
        "on-secondary": "#3d3f4f",
        "surface-container": "#191919",
        "surface": "#0e0e0e",
        "outline-variant": "#484848",
        "on-surface": "#e5e5e5",
        "primary-dim": "#7be2bd",
        "inverse-surface": "#f9f9f9",
        "secondary": "#c5c5d8",
        "surface-bright": "#2c2c2c",
        "surface-container-highest": "#262626",
        "background": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#89f0cb",
        "error": "#ff716c",
        "secondary-container": "#232533",
        "on-surface-variant": "#ababab",
        "primary": "#e7fff3",
        "inverse-primary": "#006c52",
        "secondary-dim": "#b7b7ca",
        "surface-container-high": "#1f1f1f",
        "on-primary": "#006c52",
        "outline": "#757575",
        "on-error-container": "#ff9993",
        "error-container": "#8a1a1e",
        "tertiary": "#fffadb",
        "tertiary-container": "#f1edc0",
        "tertiary-fixed": "#fdf8cb",
        "on-tertiary": "#63603e",
        "on-tertiary-container": "#5a5836",
        "on-primary-container": "#00634b",
        "surface-tint": "#e7fff3",
        "surface-dim": "#0e0e0e",
        "on-tertiary-fixed": "#4f4c2c",
        "error-dim": "#c94947",
        "on-secondary-fixed": "#404251",
        "secondary-fixed": "#e6e6fa",
        "secondary-fixed-dim": "#d8d8ec",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
